import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { AppProvider } from "./components/AppContext";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${roboto.variable}`}
      >
        <main className="max-w-4xl mx-auto p-4">
        <AppProvider>
          <Toaster/>
          <Header/>
          {children}
          <footer className="p-8 border-t text-center text-gray-500">
            © 2023 Food Ordering App. All rights reserved.
          </footer>
        </AppProvider>
        </main>
      </body>
    </html>
  );
}
